/**
 * This class is generated by jOOQ
 */
package schema.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schema.BitnamiEdx;
import schema.Keys;
import schema.tables.records.AssessmentAitrainingworkflowTrainingExamplesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssessmentAitrainingworkflowTrainingExamples extends TableImpl<AssessmentAitrainingworkflowTrainingExamplesRecord> {

    private static final long serialVersionUID = -1769566804;

    /**
     * The reference instance of <code>bitnami_edx.assessment_aitrainingworkflow_training_examples</code>
     */
    public static final AssessmentAitrainingworkflowTrainingExamples ASSESSMENT_AITRAININGWORKFLOW_TRAINING_EXAMPLES = new AssessmentAitrainingworkflowTrainingExamples();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssessmentAitrainingworkflowTrainingExamplesRecord> getRecordType() {
        return AssessmentAitrainingworkflowTrainingExamplesRecord.class;
    }

    /**
     * The column <code>bitnami_edx.assessment_aitrainingworkflow_training_examples.id</code>.
     */
    public final TableField<AssessmentAitrainingworkflowTrainingExamplesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.assessment_aitrainingworkflow_training_examples.aitrainingworkflow_id</code>.
     */
    public final TableField<AssessmentAitrainingworkflowTrainingExamplesRecord, Integer> AITRAININGWORKFLOW_ID = createField("aitrainingworkflow_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.assessment_aitrainingworkflow_training_examples.trainingexample_id</code>.
     */
    public final TableField<AssessmentAitrainingworkflowTrainingExamplesRecord, Integer> TRAININGEXAMPLE_ID = createField("trainingexample_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>bitnami_edx.assessment_aitrainingworkflow_training_examples</code> table reference
     */
    public AssessmentAitrainingworkflowTrainingExamples() {
        this("assessment_aitrainingworkflow_training_examples", null);
    }

    /**
     * Create an aliased <code>bitnami_edx.assessment_aitrainingworkflow_training_examples</code> table reference
     */
    public AssessmentAitrainingworkflowTrainingExamples(String alias) {
        this(alias, ASSESSMENT_AITRAININGWORKFLOW_TRAINING_EXAMPLES);
    }

    private AssessmentAitrainingworkflowTrainingExamples(String alias, Table<AssessmentAitrainingworkflowTrainingExamplesRecord> aliased) {
        this(alias, aliased, null);
    }

    private AssessmentAitrainingworkflowTrainingExamples(String alias, Table<AssessmentAitrainingworkflowTrainingExamplesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BitnamiEdx.BITNAMI_EDX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AssessmentAitrainingworkflowTrainingExamplesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ASSESSMENT_AITRAININGWORKFLOW_TRAINING_EXAMPLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AssessmentAitrainingworkflowTrainingExamplesRecord> getPrimaryKey() {
        return Keys.KEY_ASSESSMENT_AITRAININGWORKFLOW_TRAINING_EXAMPLES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AssessmentAitrainingworkflowTrainingExamplesRecord>> getKeys() {
        return Arrays.<UniqueKey<AssessmentAitrainingworkflowTrainingExamplesRecord>>asList(Keys.KEY_ASSESSMENT_AITRAININGWORKFLOW_TRAINING_EXAMPLES_PRIMARY, Keys.KEY_ASSESSMENT_AITRAININGWORKFLOW_TRAINING_EXAMPLES_AITRAININGWORKFLOW_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AssessmentAitrainingworkflowTrainingExamplesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AssessmentAitrainingworkflowTrainingExamplesRecord, ?>>asList(Keys.DA55BE90CAEE21D95136E40C53E5C754, Keys.FF4DDECC43BD06C0D85785A61E955133);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentAitrainingworkflowTrainingExamples as(String alias) {
        return new AssessmentAitrainingworkflowTrainingExamples(alias, this);
    }

    /**
     * Rename this table
     */
    public AssessmentAitrainingworkflowTrainingExamples rename(String name) {
        return new AssessmentAitrainingworkflowTrainingExamples(name, null);
    }
}
