/**
 * This class is generated by jOOQ
 */
package schema.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schema.BitnamiEdx;
import schema.Keys;
import schema.tables.records.CertificatesCertificatewhitelistRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CertificatesCertificatewhitelist extends TableImpl<CertificatesCertificatewhitelistRecord> {

    private static final long serialVersionUID = 631056857;

    /**
     * The reference instance of <code>bitnami_edx.certificates_certificatewhitelist</code>
     */
    public static final CertificatesCertificatewhitelist CERTIFICATES_CERTIFICATEWHITELIST = new CertificatesCertificatewhitelist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CertificatesCertificatewhitelistRecord> getRecordType() {
        return CertificatesCertificatewhitelistRecord.class;
    }

    /**
     * The column <code>bitnami_edx.certificates_certificatewhitelist.id</code>.
     */
    public final TableField<CertificatesCertificatewhitelistRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.certificates_certificatewhitelist.course_id</code>.
     */
    public final TableField<CertificatesCertificatewhitelistRecord, String> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.certificates_certificatewhitelist.whitelist</code>.
     */
    public final TableField<CertificatesCertificatewhitelistRecord, Byte> WHITELIST = createField("whitelist", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.certificates_certificatewhitelist.created</code>.
     */
    public final TableField<CertificatesCertificatewhitelistRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.certificates_certificatewhitelist.notes</code>.
     */
    public final TableField<CertificatesCertificatewhitelistRecord, String> NOTES = createField("notes", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>bitnami_edx.certificates_certificatewhitelist.user_id</code>.
     */
    public final TableField<CertificatesCertificatewhitelistRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>bitnami_edx.certificates_certificatewhitelist</code> table reference
     */
    public CertificatesCertificatewhitelist() {
        this("certificates_certificatewhitelist", null);
    }

    /**
     * Create an aliased <code>bitnami_edx.certificates_certificatewhitelist</code> table reference
     */
    public CertificatesCertificatewhitelist(String alias) {
        this(alias, CERTIFICATES_CERTIFICATEWHITELIST);
    }

    private CertificatesCertificatewhitelist(String alias, Table<CertificatesCertificatewhitelistRecord> aliased) {
        this(alias, aliased, null);
    }

    private CertificatesCertificatewhitelist(String alias, Table<CertificatesCertificatewhitelistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BitnamiEdx.BITNAMI_EDX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CertificatesCertificatewhitelistRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CERTIFICATES_CERTIFICATEWHITELIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CertificatesCertificatewhitelistRecord> getPrimaryKey() {
        return Keys.KEY_CERTIFICATES_CERTIFICATEWHITELIST_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CertificatesCertificatewhitelistRecord>> getKeys() {
        return Arrays.<UniqueKey<CertificatesCertificatewhitelistRecord>>asList(Keys.KEY_CERTIFICATES_CERTIFICATEWHITELIST_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CertificatesCertificatewhitelistRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CertificatesCertificatewhitelistRecord, ?>>asList(Keys.CERTIFICATES_CERTIFICAT_USER_ID_50B0BC90075A5407_FK_AUTH_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CertificatesCertificatewhitelist as(String alias) {
        return new CertificatesCertificatewhitelist(alias, this);
    }

    /**
     * Rename this table
     */
    public CertificatesCertificatewhitelist rename(String name) {
        return new CertificatesCertificatewhitelist(name, null);
    }
}
