/**
 * This class is generated by jOOQ
 */
package schema.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schema.BitnamiEdx;
import schema.Keys;
import schema.tables.records.DjceleryTaskstateRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjceleryTaskstate extends TableImpl<DjceleryTaskstateRecord> {

    private static final long serialVersionUID = -197282090;

    /**
     * The reference instance of <code>bitnami_edx.djcelery_taskstate</code>
     */
    public static final DjceleryTaskstate DJCELERY_TASKSTATE = new DjceleryTaskstate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DjceleryTaskstateRecord> getRecordType() {
        return DjceleryTaskstateRecord.class;
    }

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.id</code>.
     */
    public final TableField<DjceleryTaskstateRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.state</code>.
     */
    public final TableField<DjceleryTaskstateRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.task_id</code>.
     */
    public final TableField<DjceleryTaskstateRecord, String> TASK_ID = createField("task_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.name</code>.
     */
    public final TableField<DjceleryTaskstateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.tstamp</code>.
     */
    public final TableField<DjceleryTaskstateRecord, Timestamp> TSTAMP = createField("tstamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.args</code>.
     */
    public final TableField<DjceleryTaskstateRecord, String> ARGS = createField("args", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.kwargs</code>.
     */
    public final TableField<DjceleryTaskstateRecord, String> KWARGS = createField("kwargs", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.eta</code>.
     */
    public final TableField<DjceleryTaskstateRecord, Timestamp> ETA = createField("eta", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.expires</code>.
     */
    public final TableField<DjceleryTaskstateRecord, Timestamp> EXPIRES = createField("expires", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.result</code>.
     */
    public final TableField<DjceleryTaskstateRecord, String> RESULT = createField("result", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.traceback</code>.
     */
    public final TableField<DjceleryTaskstateRecord, String> TRACEBACK = createField("traceback", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.runtime</code>.
     */
    public final TableField<DjceleryTaskstateRecord, Double> RUNTIME = createField("runtime", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.retries</code>.
     */
    public final TableField<DjceleryTaskstateRecord, Integer> RETRIES = createField("retries", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.worker_id</code>.
     */
    public final TableField<DjceleryTaskstateRecord, Integer> WORKER_ID = createField("worker_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bitnami_edx.djcelery_taskstate.hidden</code>.
     */
    public final TableField<DjceleryTaskstateRecord, Byte> HIDDEN = createField("hidden", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * Create a <code>bitnami_edx.djcelery_taskstate</code> table reference
     */
    public DjceleryTaskstate() {
        this("djcelery_taskstate", null);
    }

    /**
     * Create an aliased <code>bitnami_edx.djcelery_taskstate</code> table reference
     */
    public DjceleryTaskstate(String alias) {
        this(alias, DJCELERY_TASKSTATE);
    }

    private DjceleryTaskstate(String alias, Table<DjceleryTaskstateRecord> aliased) {
        this(alias, aliased, null);
    }

    private DjceleryTaskstate(String alias, Table<DjceleryTaskstateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BitnamiEdx.BITNAMI_EDX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DjceleryTaskstateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DJCELERY_TASKSTATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DjceleryTaskstateRecord> getPrimaryKey() {
        return Keys.KEY_DJCELERY_TASKSTATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DjceleryTaskstateRecord>> getKeys() {
        return Arrays.<UniqueKey<DjceleryTaskstateRecord>>asList(Keys.KEY_DJCELERY_TASKSTATE_PRIMARY, Keys.KEY_DJCELERY_TASKSTATE_TASK_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DjceleryTaskstateRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DjceleryTaskstateRecord, ?>>asList(Keys.DJCELERY_T_WORKER_ID_30050731B1C3D3D9_FK_DJCELERY_WORKERSTATE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjceleryTaskstate as(String alias) {
        return new DjceleryTaskstate(alias, this);
    }

    /**
     * Rename this table
     */
    public DjceleryTaskstate rename(String name) {
        return new DjceleryTaskstate(name, null);
    }
}
