/**
 * This class is generated by jOOQ
 */
package schema.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schema.BitnamiEdx;
import schema.Keys;
import schema.tables.records.EmbargoCountryaccessruleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmbargoCountryaccessrule extends TableImpl<EmbargoCountryaccessruleRecord> {

    private static final long serialVersionUID = 152039861;

    /**
     * The reference instance of <code>bitnami_edx.embargo_countryaccessrule</code>
     */
    public static final EmbargoCountryaccessrule EMBARGO_COUNTRYACCESSRULE = new EmbargoCountryaccessrule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmbargoCountryaccessruleRecord> getRecordType() {
        return EmbargoCountryaccessruleRecord.class;
    }

    /**
     * The column <code>bitnami_edx.embargo_countryaccessrule.id</code>.
     */
    public final TableField<EmbargoCountryaccessruleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.embargo_countryaccessrule.rule_type</code>.
     */
    public final TableField<EmbargoCountryaccessruleRecord, String> RULE_TYPE = createField("rule_type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.embargo_countryaccessrule.country_id</code>.
     */
    public final TableField<EmbargoCountryaccessruleRecord, Integer> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.embargo_countryaccessrule.restricted_course_id</code>.
     */
    public final TableField<EmbargoCountryaccessruleRecord, Integer> RESTRICTED_COURSE_ID = createField("restricted_course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>bitnami_edx.embargo_countryaccessrule</code> table reference
     */
    public EmbargoCountryaccessrule() {
        this("embargo_countryaccessrule", null);
    }

    /**
     * Create an aliased <code>bitnami_edx.embargo_countryaccessrule</code> table reference
     */
    public EmbargoCountryaccessrule(String alias) {
        this(alias, EMBARGO_COUNTRYACCESSRULE);
    }

    private EmbargoCountryaccessrule(String alias, Table<EmbargoCountryaccessruleRecord> aliased) {
        this(alias, aliased, null);
    }

    private EmbargoCountryaccessrule(String alias, Table<EmbargoCountryaccessruleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BitnamiEdx.BITNAMI_EDX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EmbargoCountryaccessruleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EMBARGO_COUNTRYACCESSRULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EmbargoCountryaccessruleRecord> getPrimaryKey() {
        return Keys.KEY_EMBARGO_COUNTRYACCESSRULE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EmbargoCountryaccessruleRecord>> getKeys() {
        return Arrays.<UniqueKey<EmbargoCountryaccessruleRecord>>asList(Keys.KEY_EMBARGO_COUNTRYACCESSRULE_PRIMARY, Keys.KEY_EMBARGO_COUNTRYACCESSRULE_EMBARGO_COUNTRYACCESS_RESTRICTED_COURSE_ID_6F340C36C633CB0A_UNIQ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EmbargoCountryaccessruleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EmbargoCountryaccessruleRecord, ?>>asList(Keys.EMBARGO_COUNTR_COUNTRY_ID_6244FF9D9C405C6E_FK_EMBARGO_COUNTRY_ID, Keys.D140F72CCE132BA9230B3FF66D8761AD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmbargoCountryaccessrule as(String alias) {
        return new EmbargoCountryaccessrule(alias, this);
    }

    /**
     * Rename this table
     */
    public EmbargoCountryaccessrule rename(String name) {
        return new EmbargoCountryaccessrule(name, null);
    }
}
