/**
 * This class is generated by jOOQ
 */
package schema.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schema.BitnamiEdx;
import schema.Keys;
import schema.tables.records.ShoppingcartCourseregistrationcodeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShoppingcartCourseregistrationcode extends TableImpl<ShoppingcartCourseregistrationcodeRecord> {

    private static final long serialVersionUID = 1228305943;

    /**
     * The reference instance of <code>bitnami_edx.shoppingcart_courseregistrationcode</code>
     */
    public static final ShoppingcartCourseregistrationcode SHOPPINGCART_COURSEREGISTRATIONCODE = new ShoppingcartCourseregistrationcode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShoppingcartCourseregistrationcodeRecord> getRecordType() {
        return ShoppingcartCourseregistrationcodeRecord.class;
    }

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.id</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.code</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.course_id</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, String> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.created_at</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.mode_slug</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, String> MODE_SLUG = createField("mode_slug", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.is_valid</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, Byte> IS_VALID = createField("is_valid", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.created_by_id</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, Integer> CREATED_BY_ID = createField("created_by_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.invoice_id</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, Integer> INVOICE_ID = createField("invoice_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.order_id</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, Integer> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bitnami_edx.shoppingcart_courseregistrationcode.invoice_item_id</code>.
     */
    public final TableField<ShoppingcartCourseregistrationcodeRecord, Integer> INVOICE_ITEM_ID = createField("invoice_item_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>bitnami_edx.shoppingcart_courseregistrationcode</code> table reference
     */
    public ShoppingcartCourseregistrationcode() {
        this("shoppingcart_courseregistrationcode", null);
    }

    /**
     * Create an aliased <code>bitnami_edx.shoppingcart_courseregistrationcode</code> table reference
     */
    public ShoppingcartCourseregistrationcode(String alias) {
        this(alias, SHOPPINGCART_COURSEREGISTRATIONCODE);
    }

    private ShoppingcartCourseregistrationcode(String alias, Table<ShoppingcartCourseregistrationcodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ShoppingcartCourseregistrationcode(String alias, Table<ShoppingcartCourseregistrationcodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BitnamiEdx.BITNAMI_EDX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ShoppingcartCourseregistrationcodeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SHOPPINGCART_COURSEREGISTRATIONCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ShoppingcartCourseregistrationcodeRecord> getPrimaryKey() {
        return Keys.KEY_SHOPPINGCART_COURSEREGISTRATIONCODE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ShoppingcartCourseregistrationcodeRecord>> getKeys() {
        return Arrays.<UniqueKey<ShoppingcartCourseregistrationcodeRecord>>asList(Keys.KEY_SHOPPINGCART_COURSEREGISTRATIONCODE_PRIMARY, Keys.KEY_SHOPPINGCART_COURSEREGISTRATIONCODE_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ShoppingcartCourseregistrationcodeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ShoppingcartCourseregistrationcodeRecord, ?>>asList(Keys.SHOPPINGCART_COUR_CREATED_BY_ID_11125A9667AA01C9_FK_AUTH_USER_ID, Keys.SHOPPINGC_INVOICE_ID_422F26BDC7C5CB99_FK_SHOPPINGCART_INVOICE_ID, Keys.SHOPPINGCART__ORDER_ID_279D7E2DF3FE6B6A_FK_SHOPPINGCART_ORDER_ID, Keys.F040030B6361304BD87EB40C09A82094);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShoppingcartCourseregistrationcode as(String alias) {
        return new ShoppingcartCourseregistrationcode(alias, this);
    }

    /**
     * Rename this table
     */
    public ShoppingcartCourseregistrationcode rename(String name) {
        return new ShoppingcartCourseregistrationcode(name, null);
    }
}
