/**
 * This class is generated by jOOQ
 */
package schema.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schema.BitnamiEdx;
import schema.Keys;
import schema.tables.records.SurveySurveyformRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SurveySurveyform extends TableImpl<SurveySurveyformRecord> {

    private static final long serialVersionUID = -2014642124;

    /**
     * The reference instance of <code>bitnami_edx.survey_surveyform</code>
     */
    public static final SurveySurveyform SURVEY_SURVEYFORM = new SurveySurveyform();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SurveySurveyformRecord> getRecordType() {
        return SurveySurveyformRecord.class;
    }

    /**
     * The column <code>bitnami_edx.survey_surveyform.id</code>.
     */
    public final TableField<SurveySurveyformRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.survey_surveyform.created</code>.
     */
    public final TableField<SurveySurveyformRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.survey_surveyform.modified</code>.
     */
    public final TableField<SurveySurveyformRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.survey_surveyform.name</code>.
     */
    public final TableField<SurveySurveyformRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.survey_surveyform.form</code>.
     */
    public final TableField<SurveySurveyformRecord, String> FORM = createField("form", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>bitnami_edx.survey_surveyform</code> table reference
     */
    public SurveySurveyform() {
        this("survey_surveyform", null);
    }

    /**
     * Create an aliased <code>bitnami_edx.survey_surveyform</code> table reference
     */
    public SurveySurveyform(String alias) {
        this(alias, SURVEY_SURVEYFORM);
    }

    private SurveySurveyform(String alias, Table<SurveySurveyformRecord> aliased) {
        this(alias, aliased, null);
    }

    private SurveySurveyform(String alias, Table<SurveySurveyformRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BitnamiEdx.BITNAMI_EDX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SurveySurveyformRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SURVEY_SURVEYFORM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SurveySurveyformRecord> getPrimaryKey() {
        return Keys.KEY_SURVEY_SURVEYFORM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SurveySurveyformRecord>> getKeys() {
        return Arrays.<UniqueKey<SurveySurveyformRecord>>asList(Keys.KEY_SURVEY_SURVEYFORM_PRIMARY, Keys.KEY_SURVEY_SURVEYFORM_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveySurveyform as(String alias) {
        return new SurveySurveyform(alias, this);
    }

    /**
     * Rename this table
     */
    public SurveySurveyform rename(String name) {
        return new SurveySurveyform(name, null);
    }
}
