/**
 * This class is generated by jOOQ
 */
package schema.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schema.BitnamiEdx;
import schema.Keys;
import schema.tables.records.UtilRatelimitconfigurationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UtilRatelimitconfiguration extends TableImpl<UtilRatelimitconfigurationRecord> {

    private static final long serialVersionUID = -1117975752;

    /**
     * The reference instance of <code>bitnami_edx.util_ratelimitconfiguration</code>
     */
    public static final UtilRatelimitconfiguration UTIL_RATELIMITCONFIGURATION = new UtilRatelimitconfiguration();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UtilRatelimitconfigurationRecord> getRecordType() {
        return UtilRatelimitconfigurationRecord.class;
    }

    /**
     * The column <code>bitnami_edx.util_ratelimitconfiguration.id</code>.
     */
    public final TableField<UtilRatelimitconfigurationRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.util_ratelimitconfiguration.change_date</code>.
     */
    public final TableField<UtilRatelimitconfigurationRecord, Timestamp> CHANGE_DATE = createField("change_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.util_ratelimitconfiguration.enabled</code>.
     */
    public final TableField<UtilRatelimitconfigurationRecord, Byte> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.util_ratelimitconfiguration.changed_by_id</code>.
     */
    public final TableField<UtilRatelimitconfigurationRecord, Integer> CHANGED_BY_ID = createField("changed_by_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>bitnami_edx.util_ratelimitconfiguration</code> table reference
     */
    public UtilRatelimitconfiguration() {
        this("util_ratelimitconfiguration", null);
    }

    /**
     * Create an aliased <code>bitnami_edx.util_ratelimitconfiguration</code> table reference
     */
    public UtilRatelimitconfiguration(String alias) {
        this(alias, UTIL_RATELIMITCONFIGURATION);
    }

    private UtilRatelimitconfiguration(String alias, Table<UtilRatelimitconfigurationRecord> aliased) {
        this(alias, aliased, null);
    }

    private UtilRatelimitconfiguration(String alias, Table<UtilRatelimitconfigurationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BitnamiEdx.BITNAMI_EDX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UtilRatelimitconfigurationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_UTIL_RATELIMITCONFIGURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UtilRatelimitconfigurationRecord> getPrimaryKey() {
        return Keys.KEY_UTIL_RATELIMITCONFIGURATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UtilRatelimitconfigurationRecord>> getKeys() {
        return Arrays.<UniqueKey<UtilRatelimitconfigurationRecord>>asList(Keys.KEY_UTIL_RATELIMITCONFIGURATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UtilRatelimitconfigurationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UtilRatelimitconfigurationRecord, ?>>asList(Keys.UTIL_RATELIMITCON_CHANGED_BY_ID_2C8891CB4854F3B5_FK_AUTH_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UtilRatelimitconfiguration as(String alias) {
        return new UtilRatelimitconfiguration(alias, this);
    }

    /**
     * Rename this table
     */
    public UtilRatelimitconfiguration rename(String name) {
        return new UtilRatelimitconfiguration(name, null);
    }
}
