/**
 * This class is generated by jOOQ
 */
package schema.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import schema.BitnamiEdx;
import schema.Keys;
import schema.tables.records.VerifiedTrackContentVerifiedtrackcohortedcourseRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerifiedTrackContentVerifiedtrackcohortedcourse extends TableImpl<VerifiedTrackContentVerifiedtrackcohortedcourseRecord> {

    private static final long serialVersionUID = -502931924;

    /**
     * The reference instance of <code>bitnami_edx.verified_track_content_verifiedtrackcohortedcourse</code>
     */
    public static final VerifiedTrackContentVerifiedtrackcohortedcourse VERIFIED_TRACK_CONTENT_VERIFIEDTRACKCOHORTEDCOURSE = new VerifiedTrackContentVerifiedtrackcohortedcourse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VerifiedTrackContentVerifiedtrackcohortedcourseRecord> getRecordType() {
        return VerifiedTrackContentVerifiedtrackcohortedcourseRecord.class;
    }

    /**
     * The column <code>bitnami_edx.verified_track_content_verifiedtrackcohortedcourse.id</code>.
     */
    public final TableField<VerifiedTrackContentVerifiedtrackcohortedcourseRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.verified_track_content_verifiedtrackcohortedcourse.course_key</code>.
     */
    public final TableField<VerifiedTrackContentVerifiedtrackcohortedcourseRecord, String> COURSE_KEY = createField("course_key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.verified_track_content_verifiedtrackcohortedcourse.enabled</code>.
     */
    public final TableField<VerifiedTrackContentVerifiedtrackcohortedcourseRecord, Byte> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>bitnami_edx.verified_track_content_verifiedtrackcohortedcourse.verified_cohort_name</code>.
     */
    public final TableField<VerifiedTrackContentVerifiedtrackcohortedcourseRecord, String> VERIFIED_COHORT_NAME = createField("verified_cohort_name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * Create a <code>bitnami_edx.verified_track_content_verifiedtrackcohortedcourse</code> table reference
     */
    public VerifiedTrackContentVerifiedtrackcohortedcourse() {
        this("verified_track_content_verifiedtrackcohortedcourse", null);
    }

    /**
     * Create an aliased <code>bitnami_edx.verified_track_content_verifiedtrackcohortedcourse</code> table reference
     */
    public VerifiedTrackContentVerifiedtrackcohortedcourse(String alias) {
        this(alias, VERIFIED_TRACK_CONTENT_VERIFIEDTRACKCOHORTEDCOURSE);
    }

    private VerifiedTrackContentVerifiedtrackcohortedcourse(String alias, Table<VerifiedTrackContentVerifiedtrackcohortedcourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private VerifiedTrackContentVerifiedtrackcohortedcourse(String alias, Table<VerifiedTrackContentVerifiedtrackcohortedcourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BitnamiEdx.BITNAMI_EDX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VerifiedTrackContentVerifiedtrackcohortedcourseRecord, Integer> getIdentity() {
        return Keys.IDENTITY_VERIFIED_TRACK_CONTENT_VERIFIEDTRACKCOHORTEDCOURSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VerifiedTrackContentVerifiedtrackcohortedcourseRecord> getPrimaryKey() {
        return Keys.KEY_VERIFIED_TRACK_CONTENT_VERIFIEDTRACKCOHORTEDCOURSE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VerifiedTrackContentVerifiedtrackcohortedcourseRecord>> getKeys() {
        return Arrays.<UniqueKey<VerifiedTrackContentVerifiedtrackcohortedcourseRecord>>asList(Keys.KEY_VERIFIED_TRACK_CONTENT_VERIFIEDTRACKCOHORTEDCOURSE_PRIMARY, Keys.KEY_VERIFIED_TRACK_CONTENT_VERIFIEDTRACKCOHORTEDCOURSE_COURSE_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerifiedTrackContentVerifiedtrackcohortedcourse as(String alias) {
        return new VerifiedTrackContentVerifiedtrackcohortedcourse(alias, this);
    }

    /**
     * Rename this table
     */
    public VerifiedTrackContentVerifiedtrackcohortedcourse rename(String name) {
        return new VerifiedTrackContentVerifiedtrackcohortedcourse(name, null);
    }
}
