/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.ApiAdminHistoricalapiaccessrequest;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiAdminHistoricalapiaccessrequestRecord extends UpdatableRecordImpl<ApiAdminHistoricalapiaccessrequestRecord> implements Record15<Integer, Timestamp, Timestamp, String, String, String, Integer, Timestamp, String, Integer, Integer, String, String, Byte, Integer> {

    private static final long serialVersionUID = -978915703;

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.website</code>.
     */
    public void setWebsite(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.website</code>.
     */
    public String getWebsite() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.reason</code>.
     */
    public void setReason(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.reason</code>.
     */
    public String getReason() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.history_id</code>.
     */
    public void setHistoryId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.history_id</code>.
     */
    public Integer getHistoryId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.history_date</code>.
     */
    public void setHistoryDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.history_date</code>.
     */
    public Timestamp getHistoryDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.history_type</code>.
     */
    public void setHistoryType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.history_type</code>.
     */
    public String getHistoryType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.history_user_id</code>.
     */
    public void setHistoryUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.history_user_id</code>.
     */
    public Integer getHistoryUserId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.company_address</code>.
     */
    public void setCompanyAddress(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.company_address</code>.
     */
    public String getCompanyAddress() {
        return (String) get(11);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.company_name</code>.
     */
    public void setCompanyName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.company_name</code>.
     */
    public String getCompanyName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.contacted</code>.
     */
    public void setContacted(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.contacted</code>.
     */
    public Byte getContacted() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.site_id</code>.
     */
    public void setSiteId(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>bitnami_edx.api_admin_historicalapiaccessrequest.site_id</code>.
     */
    public Integer getSiteId() {
        return (Integer) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Timestamp, Timestamp, String, String, String, Integer, Timestamp, String, Integer, Integer, String, String, Byte, Integer> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Timestamp, Timestamp, String, String, String, Integer, Timestamp, String, Integer, Integer, String, String, Byte, Integer> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.HISTORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.HISTORY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.HISTORY_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.HISTORY_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.COMPANY_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.COMPANY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field14() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.CONTACTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST.SITE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getHistoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getHistoryDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getHistoryType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getHistoryUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCompanyAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value14() {
        return getContacted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getSiteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value3(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value5(String value) {
        setWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value6(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value7(Integer value) {
        setHistoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value8(Timestamp value) {
        setHistoryDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value9(String value) {
        setHistoryType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value10(Integer value) {
        setHistoryUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value11(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value12(String value) {
        setCompanyAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value13(String value) {
        setCompanyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value14(Byte value) {
        setContacted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord value15(Integer value) {
        setSiteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApiAdminHistoricalapiaccessrequestRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, String value5, String value6, Integer value7, Timestamp value8, String value9, Integer value10, Integer value11, String value12, String value13, Byte value14, Integer value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApiAdminHistoricalapiaccessrequestRecord
     */
    public ApiAdminHistoricalapiaccessrequestRecord() {
        super(ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST);
    }

    /**
     * Create a detached, initialised ApiAdminHistoricalapiaccessrequestRecord
     */
    public ApiAdminHistoricalapiaccessrequestRecord(Integer id, Timestamp created, Timestamp modified, String status, String website, String reason, Integer historyId, Timestamp historyDate, String historyType, Integer historyUserId, Integer userId, String companyAddress, String companyName, Byte contacted, Integer siteId) {
        super(ApiAdminHistoricalapiaccessrequest.API_ADMIN_HISTORICALAPIACCESSREQUEST);

        set(0, id);
        set(1, created);
        set(2, modified);
        set(3, status);
        set(4, website);
        set(5, reason);
        set(6, historyId);
        set(7, historyDate);
        set(8, historyType);
        set(9, historyUserId);
        set(10, userId);
        set(11, companyAddress);
        set(12, companyName);
        set(13, contacted);
        set(14, siteId);
    }
}
