/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.AssessmentAssessmentfeedback;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssessmentAssessmentfeedbackRecord extends UpdatableRecordImpl<AssessmentAssessmentfeedbackRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 84024207;

    /**
     * Setter for <code>bitnami_edx.assessment_assessmentfeedback.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_assessmentfeedback.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_assessmentfeedback.submission_uuid</code>.
     */
    public void setSubmissionUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_assessmentfeedback.submission_uuid</code>.
     */
    public String getSubmissionUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_assessmentfeedback.feedback_text</code>.
     */
    public void setFeedbackText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_assessmentfeedback.feedback_text</code>.
     */
    public String getFeedbackText() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AssessmentAssessmentfeedback.ASSESSMENT_ASSESSMENTFEEDBACK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AssessmentAssessmentfeedback.ASSESSMENT_ASSESSMENTFEEDBACK.SUBMISSION_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AssessmentAssessmentfeedback.ASSESSMENT_ASSESSMENTFEEDBACK.FEEDBACK_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSubmissionUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFeedbackText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentAssessmentfeedbackRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentAssessmentfeedbackRecord value2(String value) {
        setSubmissionUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentAssessmentfeedbackRecord value3(String value) {
        setFeedbackText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentAssessmentfeedbackRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssessmentAssessmentfeedbackRecord
     */
    public AssessmentAssessmentfeedbackRecord() {
        super(AssessmentAssessmentfeedback.ASSESSMENT_ASSESSMENTFEEDBACK);
    }

    /**
     * Create a detached, initialised AssessmentAssessmentfeedbackRecord
     */
    public AssessmentAssessmentfeedbackRecord(Integer id, String submissionUuid, String feedbackText) {
        super(AssessmentAssessmentfeedback.ASSESSMENT_ASSESSMENTFEEDBACK);

        set(0, id);
        set(1, submissionUuid);
        set(2, feedbackText);
    }
}
