/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.AssessmentStaffworkflow;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssessmentStaffworkflowRecord extends UpdatableRecordImpl<AssessmentStaffworkflowRecord> implements Record10<Integer, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 2103581760;

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.scorer_id</code>.
     */
    public void setScorerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.scorer_id</code>.
     */
    public String getScorerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.course_id</code>.
     */
    public void setCourseId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.course_id</code>.
     */
    public String getCourseId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.item_id</code>.
     */
    public void setItemId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.item_id</code>.
     */
    public String getItemId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.submission_uuid</code>.
     */
    public void setSubmissionUuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.submission_uuid</code>.
     */
    public String getSubmissionUuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.grading_completed_at</code>.
     */
    public void setGradingCompletedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.grading_completed_at</code>.
     */
    public Timestamp getGradingCompletedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.grading_started_at</code>.
     */
    public void setGradingStartedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.grading_started_at</code>.
     */
    public Timestamp getGradingStartedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.cancelled_at</code>.
     */
    public void setCancelledAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.cancelled_at</code>.
     */
    public Timestamp getCancelledAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_staffworkflow.assessment</code>.
     */
    public void setAssessment(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_staffworkflow.assessment</code>.
     */
    public String getAssessment() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.SCORER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.SUBMISSION_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.GRADING_COMPLETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.GRADING_STARTED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.CANCELLED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW.ASSESSMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getScorerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSubmissionUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getGradingCompletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getGradingStartedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCancelledAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAssessment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value2(String value) {
        setScorerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value3(String value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value4(String value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value5(String value) {
        setSubmissionUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value7(Timestamp value) {
        setGradingCompletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value8(Timestamp value) {
        setGradingStartedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value9(Timestamp value) {
        setCancelledAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord value10(String value) {
        setAssessment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentStaffworkflowRecord values(Integer value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, Timestamp value8, Timestamp value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssessmentStaffworkflowRecord
     */
    public AssessmentStaffworkflowRecord() {
        super(AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW);
    }

    /**
     * Create a detached, initialised AssessmentStaffworkflowRecord
     */
    public AssessmentStaffworkflowRecord(Integer id, String scorerId, String courseId, String itemId, String submissionUuid, Timestamp createdAt, Timestamp gradingCompletedAt, Timestamp gradingStartedAt, Timestamp cancelledAt, String assessment) {
        super(AssessmentStaffworkflow.ASSESSMENT_STAFFWORKFLOW);

        set(0, id);
        set(1, scorerId);
        set(2, courseId);
        set(3, itemId);
        set(4, submissionUuid);
        set(5, createdAt);
        set(6, gradingCompletedAt);
        set(7, gradingStartedAt);
        set(8, cancelledAt);
        set(9, assessment);
    }
}
