/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.AssessmentAssessmentfeedbackoption;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssessmentAssessmentfeedbackoptionRecord extends UpdatableRecordImpl<AssessmentAssessmentfeedbackoptionRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -300806938;

    /**
     * Setter for <code>bitnami_edx.assessment_assessmentfeedbackoption.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_assessmentfeedbackoption.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.assessment_assessmentfeedbackoption.text</code>.
     */
    public void setText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.assessment_assessmentfeedbackoption.text</code>.
     */
    public String getText() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AssessmentAssessmentfeedbackoption.ASSESSMENT_ASSESSMENTFEEDBACKOPTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AssessmentAssessmentfeedbackoption.ASSESSMENT_ASSESSMENTFEEDBACKOPTION.TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentAssessmentfeedbackoptionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentAssessmentfeedbackoptionRecord value2(String value) {
        setText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssessmentAssessmentfeedbackoptionRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssessmentAssessmentfeedbackoptionRecord
     */
    public AssessmentAssessmentfeedbackoptionRecord() {
        super(AssessmentAssessmentfeedbackoption.ASSESSMENT_ASSESSMENTFEEDBACKOPTION);
    }

    /**
     * Create a detached, initialised AssessmentAssessmentfeedbackoptionRecord
     */
    public AssessmentAssessmentfeedbackoptionRecord(Integer id, String text) {
        super(AssessmentAssessmentfeedbackoption.ASSESSMENT_ASSESSMENTFEEDBACKOPTION);

        set(0, id);
        set(1, text);
    }
}
