/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.BookmarksBookmark;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookmarksBookmarkRecord extends UpdatableRecordImpl<BookmarksBookmarkRecord> implements Record8<Integer, Timestamp, Timestamp, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1492664677;

    /**
     * Setter for <code>bitnami_edx.bookmarks_bookmark.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.bookmarks_bookmark.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.bookmarks_bookmark.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.bookmarks_bookmark.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.bookmarks_bookmark.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.bookmarks_bookmark.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.bookmarks_bookmark.course_key</code>.
     */
    public void setCourseKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.bookmarks_bookmark.course_key</code>.
     */
    public String getCourseKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.bookmarks_bookmark.usage_key</code>.
     */
    public void setUsageKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.bookmarks_bookmark.usage_key</code>.
     */
    public String getUsageKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.bookmarks_bookmark.path</code>.
     */
    public void setPath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.bookmarks_bookmark.path</code>.
     */
    public String getPath() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bitnami_edx.bookmarks_bookmark.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>bitnami_edx.bookmarks_bookmark.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>bitnami_edx.bookmarks_bookmark.xblock_cache_id</code>.
     */
    public void setXblockCacheId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>bitnami_edx.bookmarks_bookmark.xblock_cache_id</code>.
     */
    public Integer getXblockCacheId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Timestamp, Timestamp, String, String, String, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Timestamp, Timestamp, String, String, String, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BookmarksBookmark.BOOKMARKS_BOOKMARK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return BookmarksBookmark.BOOKMARKS_BOOKMARK.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return BookmarksBookmark.BOOKMARKS_BOOKMARK.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BookmarksBookmark.BOOKMARKS_BOOKMARK.COURSE_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BookmarksBookmark.BOOKMARKS_BOOKMARK.USAGE_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BookmarksBookmark.BOOKMARKS_BOOKMARK.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return BookmarksBookmark.BOOKMARKS_BOOKMARK.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return BookmarksBookmark.BOOKMARKS_BOOKMARK.XBLOCK_CACHE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCourseKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsageKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getXblockCacheId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookmarksBookmarkRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookmarksBookmarkRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookmarksBookmarkRecord value3(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookmarksBookmarkRecord value4(String value) {
        setCourseKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookmarksBookmarkRecord value5(String value) {
        setUsageKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookmarksBookmarkRecord value6(String value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookmarksBookmarkRecord value7(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookmarksBookmarkRecord value8(Integer value) {
        setXblockCacheId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookmarksBookmarkRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, String value5, String value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookmarksBookmarkRecord
     */
    public BookmarksBookmarkRecord() {
        super(BookmarksBookmark.BOOKMARKS_BOOKMARK);
    }

    /**
     * Create a detached, initialised BookmarksBookmarkRecord
     */
    public BookmarksBookmarkRecord(Integer id, Timestamp created, Timestamp modified, String courseKey, String usageKey, String path, Integer userId, Integer xblockCacheId) {
        super(BookmarksBookmark.BOOKMARKS_BOOKMARK);

        set(0, id);
        set(1, created);
        set(2, modified);
        set(3, courseKey);
        set(4, usageKey);
        set(5, path);
        set(6, userId);
        set(7, xblockCacheId);
    }
}
