/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.CoursewareXmoduleuserstatesummaryfield;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoursewareXmoduleuserstatesummaryfieldRecord extends UpdatableRecordImpl<CoursewareXmoduleuserstatesummaryfieldRecord> implements Record6<Integer, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = -1720171252;

    /**
     * Setter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.field_name</code>.
     */
    public void setFieldName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.field_name</code>.
     */
    public String getFieldName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.usage_id</code>.
     */
    public void setUsageId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.courseware_xmoduleuserstatesummaryfield.usage_id</code>.
     */
    public String getUsageId() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CoursewareXmoduleuserstatesummaryfield.COURSEWARE_XMODULEUSERSTATESUMMARYFIELD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CoursewareXmoduleuserstatesummaryfield.COURSEWARE_XMODULEUSERSTATESUMMARYFIELD.FIELD_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CoursewareXmoduleuserstatesummaryfield.COURSEWARE_XMODULEUSERSTATESUMMARYFIELD.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return CoursewareXmoduleuserstatesummaryfield.COURSEWARE_XMODULEUSERSTATESUMMARYFIELD.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return CoursewareXmoduleuserstatesummaryfield.COURSEWARE_XMODULEUSERSTATESUMMARYFIELD.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CoursewareXmoduleuserstatesummaryfield.COURSEWARE_XMODULEUSERSTATESUMMARYFIELD.USAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFieldName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUsageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoursewareXmoduleuserstatesummaryfieldRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoursewareXmoduleuserstatesummaryfieldRecord value2(String value) {
        setFieldName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoursewareXmoduleuserstatesummaryfieldRecord value3(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoursewareXmoduleuserstatesummaryfieldRecord value4(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoursewareXmoduleuserstatesummaryfieldRecord value5(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoursewareXmoduleuserstatesummaryfieldRecord value6(String value) {
        setUsageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoursewareXmoduleuserstatesummaryfieldRecord values(Integer value1, String value2, String value3, Timestamp value4, Timestamp value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoursewareXmoduleuserstatesummaryfieldRecord
     */
    public CoursewareXmoduleuserstatesummaryfieldRecord() {
        super(CoursewareXmoduleuserstatesummaryfield.COURSEWARE_XMODULEUSERSTATESUMMARYFIELD);
    }

    /**
     * Create a detached, initialised CoursewareXmoduleuserstatesummaryfieldRecord
     */
    public CoursewareXmoduleuserstatesummaryfieldRecord(Integer id, String fieldName, String value, Timestamp created, Timestamp modified, String usageId) {
        super(CoursewareXmoduleuserstatesummaryfield.COURSEWARE_XMODULEUSERSTATESUMMARYFIELD);

        set(0, id);
        set(1, fieldName);
        set(2, value);
        set(3, created);
        set(4, modified);
        set(5, usageId);
    }
}
