/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.DjceleryCrontabschedule;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjceleryCrontabscheduleRecord extends UpdatableRecordImpl<DjceleryCrontabscheduleRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 57677353;

    /**
     * Setter for <code>bitnami_edx.djcelery_crontabschedule.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.djcelery_crontabschedule.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.djcelery_crontabschedule.minute</code>.
     */
    public void setMinute(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.djcelery_crontabschedule.minute</code>.
     */
    public String getMinute() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.djcelery_crontabschedule.hour</code>.
     */
    public void setHour(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.djcelery_crontabschedule.hour</code>.
     */
    public String getHour() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.djcelery_crontabschedule.day_of_week</code>.
     */
    public void setDayOfWeek(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.djcelery_crontabschedule.day_of_week</code>.
     */
    public String getDayOfWeek() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.djcelery_crontabschedule.day_of_month</code>.
     */
    public void setDayOfMonth(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.djcelery_crontabschedule.day_of_month</code>.
     */
    public String getDayOfMonth() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.djcelery_crontabschedule.month_of_year</code>.
     */
    public void setMonthOfYear(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.djcelery_crontabschedule.month_of_year</code>.
     */
    public String getMonthOfYear() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DjceleryCrontabschedule.DJCELERY_CRONTABSCHEDULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DjceleryCrontabschedule.DJCELERY_CRONTABSCHEDULE.MINUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DjceleryCrontabschedule.DJCELERY_CRONTABSCHEDULE.HOUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DjceleryCrontabschedule.DJCELERY_CRONTABSCHEDULE.DAY_OF_WEEK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DjceleryCrontabschedule.DJCELERY_CRONTABSCHEDULE.DAY_OF_MONTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DjceleryCrontabschedule.DJCELERY_CRONTABSCHEDULE.MONTH_OF_YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMinute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getHour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDayOfWeek();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDayOfMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMonthOfYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjceleryCrontabscheduleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjceleryCrontabscheduleRecord value2(String value) {
        setMinute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjceleryCrontabscheduleRecord value3(String value) {
        setHour(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjceleryCrontabscheduleRecord value4(String value) {
        setDayOfWeek(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjceleryCrontabscheduleRecord value5(String value) {
        setDayOfMonth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjceleryCrontabscheduleRecord value6(String value) {
        setMonthOfYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjceleryCrontabscheduleRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DjceleryCrontabscheduleRecord
     */
    public DjceleryCrontabscheduleRecord() {
        super(DjceleryCrontabschedule.DJCELERY_CRONTABSCHEDULE);
    }

    /**
     * Create a detached, initialised DjceleryCrontabscheduleRecord
     */
    public DjceleryCrontabscheduleRecord(Integer id, String minute, String hour, String dayOfWeek, String dayOfMonth, String monthOfYear) {
        super(DjceleryCrontabschedule.DJCELERY_CRONTABSCHEDULE);

        set(0, id);
        set(1, minute);
        set(2, hour);
        set(3, dayOfWeek);
        set(4, dayOfMonth);
        set(5, monthOfYear);
    }
}
