/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.EdxvalVideo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EdxvalVideoRecord extends UpdatableRecordImpl<EdxvalVideoRecord> implements Record6<Integer, Timestamp, String, String, Double, String> {

    private static final long serialVersionUID = -609437384;

    /**
     * Setter for <code>bitnami_edx.edxval_video.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.edxval_video.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.edxval_video.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.edxval_video.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.edxval_video.edx_video_id</code>.
     */
    public void setEdxVideoId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.edxval_video.edx_video_id</code>.
     */
    public String getEdxVideoId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.edxval_video.client_video_id</code>.
     */
    public void setClientVideoId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.edxval_video.client_video_id</code>.
     */
    public String getClientVideoId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.edxval_video.duration</code>.
     */
    public void setDuration(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.edxval_video.duration</code>.
     */
    public Double getDuration() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.edxval_video.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.edxval_video.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, String, String, Double, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, String, String, Double, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EdxvalVideo.EDXVAL_VIDEO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return EdxvalVideo.EDXVAL_VIDEO.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EdxvalVideo.EDXVAL_VIDEO.EDX_VIDEO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return EdxvalVideo.EDXVAL_VIDEO.CLIENT_VIDEO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return EdxvalVideo.EDXVAL_VIDEO.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return EdxvalVideo.EDXVAL_VIDEO.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEdxVideoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getClientVideoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdxvalVideoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdxvalVideoRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdxvalVideoRecord value3(String value) {
        setEdxVideoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdxvalVideoRecord value4(String value) {
        setClientVideoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdxvalVideoRecord value5(Double value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdxvalVideoRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdxvalVideoRecord values(Integer value1, Timestamp value2, String value3, String value4, Double value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EdxvalVideoRecord
     */
    public EdxvalVideoRecord() {
        super(EdxvalVideo.EDXVAL_VIDEO);
    }

    /**
     * Create a detached, initialised EdxvalVideoRecord
     */
    public EdxvalVideoRecord(Integer id, Timestamp created, String edxVideoId, String clientVideoId, Double duration, String status) {
        super(EdxvalVideo.EDXVAL_VIDEO);

        set(0, id);
        set(1, created);
        set(2, edxVideoId);
        set(3, clientVideoId);
        set(4, duration);
        set(5, status);
    }
}
