/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.EmbargoIpfilter;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmbargoIpfilterRecord extends UpdatableRecordImpl<EmbargoIpfilterRecord> implements Record6<Integer, Timestamp, Byte, String, String, Integer> {

    private static final long serialVersionUID = -1558890980;

    /**
     * Setter for <code>bitnami_edx.embargo_ipfilter.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.embargo_ipfilter.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.embargo_ipfilter.change_date</code>.
     */
    public void setChangeDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.embargo_ipfilter.change_date</code>.
     */
    public Timestamp getChangeDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.embargo_ipfilter.enabled</code>.
     */
    public void setEnabled(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.embargo_ipfilter.enabled</code>.
     */
    public Byte getEnabled() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.embargo_ipfilter.whitelist</code>.
     */
    public void setWhitelist(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.embargo_ipfilter.whitelist</code>.
     */
    public String getWhitelist() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.embargo_ipfilter.blacklist</code>.
     */
    public void setBlacklist(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.embargo_ipfilter.blacklist</code>.
     */
    public String getBlacklist() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.embargo_ipfilter.changed_by_id</code>.
     */
    public void setChangedById(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.embargo_ipfilter.changed_by_id</code>.
     */
    public Integer getChangedById() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Byte, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Byte, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EmbargoIpfilter.EMBARGO_IPFILTER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return EmbargoIpfilter.EMBARGO_IPFILTER.CHANGE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return EmbargoIpfilter.EMBARGO_IPFILTER.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return EmbargoIpfilter.EMBARGO_IPFILTER.WHITELIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return EmbargoIpfilter.EMBARGO_IPFILTER.BLACKLIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return EmbargoIpfilter.EMBARGO_IPFILTER.CHANGED_BY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getChangeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getWhitelist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBlacklist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getChangedById();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmbargoIpfilterRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmbargoIpfilterRecord value2(Timestamp value) {
        setChangeDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmbargoIpfilterRecord value3(Byte value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmbargoIpfilterRecord value4(String value) {
        setWhitelist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmbargoIpfilterRecord value5(String value) {
        setBlacklist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmbargoIpfilterRecord value6(Integer value) {
        setChangedById(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmbargoIpfilterRecord values(Integer value1, Timestamp value2, Byte value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmbargoIpfilterRecord
     */
    public EmbargoIpfilterRecord() {
        super(EmbargoIpfilter.EMBARGO_IPFILTER);
    }

    /**
     * Create a detached, initialised EmbargoIpfilterRecord
     */
    public EmbargoIpfilterRecord(Integer id, Timestamp changeDate, Byte enabled, String whitelist, String blacklist, Integer changedById) {
        super(EmbargoIpfilter.EMBARGO_IPFILTER);

        set(0, id);
        set(1, changeDate);
        set(2, enabled);
        set(3, whitelist);
        set(4, blacklist);
        set(5, changedById);
    }
}
