/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.ExternalAuthExternalauthmap;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExternalAuthExternalauthmapRecord extends UpdatableRecordImpl<ExternalAuthExternalauthmapRecord> implements Record10<Integer, String, String, String, String, String, String, Timestamp, Timestamp, Integer> {

    private static final long serialVersionUID = 72749164;

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.external_id</code>.
     */
    public void setExternalId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.external_domain</code>.
     */
    public void setExternalDomain(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.external_domain</code>.
     */
    public String getExternalDomain() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.external_credentials</code>.
     */
    public void setExternalCredentials(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.external_credentials</code>.
     */
    public String getExternalCredentials() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.external_email</code>.
     */
    public void setExternalEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.external_email</code>.
     */
    public String getExternalEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.external_name</code>.
     */
    public void setExternalName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.external_name</code>.
     */
    public String getExternalName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.internal_password</code>.
     */
    public void setInternalPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.internal_password</code>.
     */
    public String getInternalPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.dtcreated</code>.
     */
    public void setDtcreated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.dtcreated</code>.
     */
    public Timestamp getDtcreated() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.dtsignup</code>.
     */
    public void setDtsignup(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.dtsignup</code>.
     */
    public Timestamp getDtsignup() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>bitnami_edx.external_auth_externalauthmap.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>bitnami_edx.external_auth_externalauthmap.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, Timestamp, Timestamp, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, Timestamp, Timestamp, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.EXTERNAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.EXTERNAL_DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.EXTERNAL_CREDENTIALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.EXTERNAL_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.EXTERNAL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.INTERNAL_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.DTCREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.DTSIGNUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExternalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getExternalDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getExternalCredentials();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getExternalEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getExternalName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getInternalPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDtcreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDtsignup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value2(String value) {
        setExternalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value3(String value) {
        setExternalDomain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value4(String value) {
        setExternalCredentials(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value5(String value) {
        setExternalEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value6(String value) {
        setExternalName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value7(String value) {
        setInternalPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value8(Timestamp value) {
        setDtcreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value9(Timestamp value) {
        setDtsignup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord value10(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalAuthExternalauthmapRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExternalAuthExternalauthmapRecord
     */
    public ExternalAuthExternalauthmapRecord() {
        super(ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP);
    }

    /**
     * Create a detached, initialised ExternalAuthExternalauthmapRecord
     */
    public ExternalAuthExternalauthmapRecord(Integer id, String externalId, String externalDomain, String externalCredentials, String externalEmail, String externalName, String internalPassword, Timestamp dtcreated, Timestamp dtsignup, Integer userId) {
        super(ExternalAuthExternalauthmap.EXTERNAL_AUTH_EXTERNALAUTHMAP);

        set(0, id);
        set(1, externalId);
        set(2, externalDomain);
        set(3, externalCredentials);
        set(4, externalEmail);
        set(5, externalName);
        set(6, internalPassword);
        set(7, dtcreated);
        set(8, dtsignup);
        set(9, userId);
    }
}
