/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.MicrositeConfigurationMicrositeorganizationmapping;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MicrositeConfigurationMicrositeorganizationmappingRecord extends UpdatableRecordImpl<MicrositeConfigurationMicrositeorganizationmappingRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 448294422;

    /**
     * Setter for <code>bitnami_edx.microsite_configuration_micrositeorganizationmapping.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.microsite_configuration_micrositeorganizationmapping.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.microsite_configuration_micrositeorganizationmapping.organization</code>.
     */
    public void setOrganization(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.microsite_configuration_micrositeorganizationmapping.organization</code>.
     */
    public String getOrganization() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.microsite_configuration_micrositeorganizationmapping.microsite_id</code>.
     */
    public void setMicrositeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.microsite_configuration_micrositeorganizationmapping.microsite_id</code>.
     */
    public Integer getMicrositeId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MicrositeConfigurationMicrositeorganizationmapping.MICROSITE_CONFIGURATION_MICROSITEORGANIZATIONMAPPING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MicrositeConfigurationMicrositeorganizationmapping.MICROSITE_CONFIGURATION_MICROSITEORGANIZATIONMAPPING.ORGANIZATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MicrositeConfigurationMicrositeorganizationmapping.MICROSITE_CONFIGURATION_MICROSITEORGANIZATIONMAPPING.MICROSITE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMicrositeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MicrositeConfigurationMicrositeorganizationmappingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MicrositeConfigurationMicrositeorganizationmappingRecord value2(String value) {
        setOrganization(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MicrositeConfigurationMicrositeorganizationmappingRecord value3(Integer value) {
        setMicrositeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MicrositeConfigurationMicrositeorganizationmappingRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MicrositeConfigurationMicrositeorganizationmappingRecord
     */
    public MicrositeConfigurationMicrositeorganizationmappingRecord() {
        super(MicrositeConfigurationMicrositeorganizationmapping.MICROSITE_CONFIGURATION_MICROSITEORGANIZATIONMAPPING);
    }

    /**
     * Create a detached, initialised MicrositeConfigurationMicrositeorganizationmappingRecord
     */
    public MicrositeConfigurationMicrositeorganizationmappingRecord(Integer id, String organization, Integer micrositeId) {
        super(MicrositeConfigurationMicrositeorganizationmapping.MICROSITE_CONFIGURATION_MICROSITEORGANIZATIONMAPPING);

        set(0, id);
        set(1, organization);
        set(2, micrositeId);
    }
}
