/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.OrganizationsOrganizationcourse;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationsOrganizationcourseRecord extends UpdatableRecordImpl<OrganizationsOrganizationcourseRecord> implements Record6<Integer, Timestamp, Timestamp, String, Byte, Integer> {

    private static final long serialVersionUID = -1793897870;

    /**
     * Setter for <code>bitnami_edx.organizations_organizationcourse.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.organizations_organizationcourse.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.organizations_organizationcourse.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.organizations_organizationcourse.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.organizations_organizationcourse.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.organizations_organizationcourse.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.organizations_organizationcourse.course_id</code>.
     */
    public void setCourseId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.organizations_organizationcourse.course_id</code>.
     */
    public String getCourseId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.organizations_organizationcourse.active</code>.
     */
    public void setActive(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.organizations_organizationcourse.active</code>.
     */
    public Byte getActive() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.organizations_organizationcourse.organization_id</code>.
     */
    public void setOrganizationId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.organizations_organizationcourse.organization_id</code>.
     */
    public Integer getOrganizationId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, String, Byte, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, String, Byte, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrganizationsOrganizationcourse.ORGANIZATIONS_ORGANIZATIONCOURSE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return OrganizationsOrganizationcourse.ORGANIZATIONS_ORGANIZATIONCOURSE.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return OrganizationsOrganizationcourse.ORGANIZATIONS_ORGANIZATIONCOURSE.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OrganizationsOrganizationcourse.ORGANIZATIONS_ORGANIZATIONCOURSE.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return OrganizationsOrganizationcourse.ORGANIZATIONS_ORGANIZATIONCOURSE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return OrganizationsOrganizationcourse.ORGANIZATIONS_ORGANIZATIONCOURSE.ORGANIZATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsOrganizationcourseRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsOrganizationcourseRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsOrganizationcourseRecord value3(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsOrganizationcourseRecord value4(String value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsOrganizationcourseRecord value5(Byte value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsOrganizationcourseRecord value6(Integer value) {
        setOrganizationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsOrganizationcourseRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, Byte value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationsOrganizationcourseRecord
     */
    public OrganizationsOrganizationcourseRecord() {
        super(OrganizationsOrganizationcourse.ORGANIZATIONS_ORGANIZATIONCOURSE);
    }

    /**
     * Create a detached, initialised OrganizationsOrganizationcourseRecord
     */
    public OrganizationsOrganizationcourseRecord(Integer id, Timestamp created, Timestamp modified, String courseId, Byte active, Integer organizationId) {
        super(OrganizationsOrganizationcourse.ORGANIZATIONS_ORGANIZATIONCOURSE);

        set(0, id);
        set(1, created);
        set(2, modified);
        set(3, courseId);
        set(4, active);
        set(5, organizationId);
    }
}
