/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.ShoppingcartInvoicehistory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShoppingcartInvoicehistoryRecord extends UpdatableRecordImpl<ShoppingcartInvoicehistoryRecord> implements Record4<Integer, Timestamp, String, Integer> {

    private static final long serialVersionUID = 366562449;

    /**
     * Setter for <code>bitnami_edx.shoppingcart_invoicehistory.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.shoppingcart_invoicehistory.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.shoppingcart_invoicehistory.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.shoppingcart_invoicehistory.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.shoppingcart_invoicehistory.snapshot</code>.
     */
    public void setSnapshot(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.shoppingcart_invoicehistory.snapshot</code>.
     */
    public String getSnapshot() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.shoppingcart_invoicehistory.invoice_id</code>.
     */
    public void setInvoiceId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.shoppingcart_invoicehistory.invoice_id</code>.
     */
    public Integer getInvoiceId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ShoppingcartInvoicehistory.SHOPPINGCART_INVOICEHISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return ShoppingcartInvoicehistory.SHOPPINGCART_INVOICEHISTORY.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ShoppingcartInvoicehistory.SHOPPINGCART_INVOICEHISTORY.SNAPSHOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ShoppingcartInvoicehistory.SHOPPINGCART_INVOICEHISTORY.INVOICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSnapshot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShoppingcartInvoicehistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShoppingcartInvoicehistoryRecord value2(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShoppingcartInvoicehistoryRecord value3(String value) {
        setSnapshot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShoppingcartInvoicehistoryRecord value4(Integer value) {
        setInvoiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShoppingcartInvoicehistoryRecord values(Integer value1, Timestamp value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShoppingcartInvoicehistoryRecord
     */
    public ShoppingcartInvoicehistoryRecord() {
        super(ShoppingcartInvoicehistory.SHOPPINGCART_INVOICEHISTORY);
    }

    /**
     * Create a detached, initialised ShoppingcartInvoicehistoryRecord
     */
    public ShoppingcartInvoicehistoryRecord(Integer id, Timestamp timestamp, String snapshot, Integer invoiceId) {
        super(ShoppingcartInvoicehistory.SHOPPINGCART_INVOICEHISTORY);

        set(0, id);
        set(1, timestamp);
        set(2, snapshot);
        set(3, invoiceId);
    }
}
