/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.StudentLanguageproficiency;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentLanguageproficiencyRecord extends UpdatableRecordImpl<StudentLanguageproficiencyRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1432647618;

    /**
     * Setter for <code>bitnami_edx.student_languageproficiency.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.student_languageproficiency.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.student_languageproficiency.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.student_languageproficiency.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.student_languageproficiency.user_profile_id</code>.
     */
    public void setUserProfileId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.student_languageproficiency.user_profile_id</code>.
     */
    public Integer getUserProfileId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StudentLanguageproficiency.STUDENT_LANGUAGEPROFICIENCY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StudentLanguageproficiency.STUDENT_LANGUAGEPROFICIENCY.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return StudentLanguageproficiency.STUDENT_LANGUAGEPROFICIENCY.USER_PROFILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserProfileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentLanguageproficiencyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentLanguageproficiencyRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentLanguageproficiencyRecord value3(Integer value) {
        setUserProfileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentLanguageproficiencyRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentLanguageproficiencyRecord
     */
    public StudentLanguageproficiencyRecord() {
        super(StudentLanguageproficiency.STUDENT_LANGUAGEPROFICIENCY);
    }

    /**
     * Create a detached, initialised StudentLanguageproficiencyRecord
     */
    public StudentLanguageproficiencyRecord(Integer id, String code, Integer userProfileId) {
        super(StudentLanguageproficiency.STUDENT_LANGUAGEPROFICIENCY);

        set(0, id);
        set(1, code);
        set(2, userProfileId);
    }
}
