/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.StudentEnrollmentrefundconfiguration;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentEnrollmentrefundconfigurationRecord extends UpdatableRecordImpl<StudentEnrollmentrefundconfigurationRecord> implements Record5<Integer, Timestamp, Byte, Long, Integer> {

    private static final long serialVersionUID = -80043928;

    /**
     * Setter for <code>bitnami_edx.student_enrollmentrefundconfiguration.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.student_enrollmentrefundconfiguration.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.student_enrollmentrefundconfiguration.change_date</code>.
     */
    public void setChangeDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.student_enrollmentrefundconfiguration.change_date</code>.
     */
    public Timestamp getChangeDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.student_enrollmentrefundconfiguration.enabled</code>.
     */
    public void setEnabled(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.student_enrollmentrefundconfiguration.enabled</code>.
     */
    public Byte getEnabled() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.student_enrollmentrefundconfiguration.refund_window_microseconds</code>.
     */
    public void setRefundWindowMicroseconds(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.student_enrollmentrefundconfiguration.refund_window_microseconds</code>.
     */
    public Long getRefundWindowMicroseconds() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.student_enrollmentrefundconfiguration.changed_by_id</code>.
     */
    public void setChangedById(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.student_enrollmentrefundconfiguration.changed_by_id</code>.
     */
    public Integer getChangedById() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, Byte, Long, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, Byte, Long, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StudentEnrollmentrefundconfiguration.STUDENT_ENROLLMENTREFUNDCONFIGURATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return StudentEnrollmentrefundconfiguration.STUDENT_ENROLLMENTREFUNDCONFIGURATION.CHANGE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return StudentEnrollmentrefundconfiguration.STUDENT_ENROLLMENTREFUNDCONFIGURATION.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return StudentEnrollmentrefundconfiguration.STUDENT_ENROLLMENTREFUNDCONFIGURATION.REFUND_WINDOW_MICROSECONDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return StudentEnrollmentrefundconfiguration.STUDENT_ENROLLMENTREFUNDCONFIGURATION.CHANGED_BY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getChangeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getRefundWindowMicroseconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getChangedById();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentEnrollmentrefundconfigurationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentEnrollmentrefundconfigurationRecord value2(Timestamp value) {
        setChangeDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentEnrollmentrefundconfigurationRecord value3(Byte value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentEnrollmentrefundconfigurationRecord value4(Long value) {
        setRefundWindowMicroseconds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentEnrollmentrefundconfigurationRecord value5(Integer value) {
        setChangedById(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentEnrollmentrefundconfigurationRecord values(Integer value1, Timestamp value2, Byte value3, Long value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentEnrollmentrefundconfigurationRecord
     */
    public StudentEnrollmentrefundconfigurationRecord() {
        super(StudentEnrollmentrefundconfiguration.STUDENT_ENROLLMENTREFUNDCONFIGURATION);
    }

    /**
     * Create a detached, initialised StudentEnrollmentrefundconfigurationRecord
     */
    public StudentEnrollmentrefundconfigurationRecord(Integer id, Timestamp changeDate, Byte enabled, Long refundWindowMicroseconds, Integer changedById) {
        super(StudentEnrollmentrefundconfiguration.STUDENT_ENROLLMENTREFUNDCONFIGURATION);

        set(0, id);
        set(1, changeDate);
        set(2, enabled);
        set(3, refundWindowMicroseconds);
        set(4, changedById);
    }
}
