/**
 * This class is generated by jOOQ
 */
package schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.VerifyStudentVerificationdeadline;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerifyStudentVerificationdeadlineRecord extends UpdatableRecordImpl<VerifyStudentVerificationdeadlineRecord> implements Record6<Integer, Timestamp, Timestamp, String, Timestamp, Byte> {

    private static final long serialVersionUID = 162609871;

    /**
     * Setter for <code>bitnami_edx.verify_student_verificationdeadline.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bitnami_edx.verify_student_verificationdeadline.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bitnami_edx.verify_student_verificationdeadline.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>bitnami_edx.verify_student_verificationdeadline.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>bitnami_edx.verify_student_verificationdeadline.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>bitnami_edx.verify_student_verificationdeadline.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>bitnami_edx.verify_student_verificationdeadline.course_key</code>.
     */
    public void setCourseKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bitnami_edx.verify_student_verificationdeadline.course_key</code>.
     */
    public String getCourseKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bitnami_edx.verify_student_verificationdeadline.deadline</code>.
     */
    public void setDeadline(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>bitnami_edx.verify_student_verificationdeadline.deadline</code>.
     */
    public Timestamp getDeadline() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>bitnami_edx.verify_student_verificationdeadline.deadline_is_explicit</code>.
     */
    public void setDeadlineIsExplicit(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>bitnami_edx.verify_student_verificationdeadline.deadline_is_explicit</code>.
     */
    public Byte getDeadlineIsExplicit() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, String, Timestamp, Byte> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, String, Timestamp, Byte> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VerifyStudentVerificationdeadline.VERIFY_STUDENT_VERIFICATIONDEADLINE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return VerifyStudentVerificationdeadline.VERIFY_STUDENT_VERIFICATIONDEADLINE.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return VerifyStudentVerificationdeadline.VERIFY_STUDENT_VERIFICATIONDEADLINE.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VerifyStudentVerificationdeadline.VERIFY_STUDENT_VERIFICATIONDEADLINE.COURSE_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return VerifyStudentVerificationdeadline.VERIFY_STUDENT_VERIFICATIONDEADLINE.DEADLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return VerifyStudentVerificationdeadline.VERIFY_STUDENT_VERIFICATIONDEADLINE.DEADLINE_IS_EXPLICIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCourseKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getDeadlineIsExplicit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerifyStudentVerificationdeadlineRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerifyStudentVerificationdeadlineRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerifyStudentVerificationdeadlineRecord value3(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerifyStudentVerificationdeadlineRecord value4(String value) {
        setCourseKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerifyStudentVerificationdeadlineRecord value5(Timestamp value) {
        setDeadline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerifyStudentVerificationdeadlineRecord value6(Byte value) {
        setDeadlineIsExplicit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerifyStudentVerificationdeadlineRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, Timestamp value5, Byte value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VerifyStudentVerificationdeadlineRecord
     */
    public VerifyStudentVerificationdeadlineRecord() {
        super(VerifyStudentVerificationdeadline.VERIFY_STUDENT_VERIFICATIONDEADLINE);
    }

    /**
     * Create a detached, initialised VerifyStudentVerificationdeadlineRecord
     */
    public VerifyStudentVerificationdeadlineRecord(Integer id, Timestamp created, Timestamp modified, String courseKey, Timestamp deadline, Byte deadlineIsExplicit) {
        super(VerifyStudentVerificationdeadline.VERIFY_STUDENT_VERIFICATIONDEADLINE);

        set(0, id);
        set(1, created);
        set(2, modified);
        set(3, courseKey);
        set(4, deadline);
        set(5, deadlineIsExplicit);
    }
}
